### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by codebreaker332** [0iskak/steam-account-switcher#1]
hello, i would like to use your project, could you give me instructions on how to compile or could you post the already compiled file? I'm noob, thank you

**Comment by 0iskak** [comment]
wow, nice to see you.
I will post instructions during the day.

**Comment by 0iskak** [comment]
or here is the compiled one https://github.com/0iskak/steam-account-switcher/releases/tag/0.1

[steam-account-switcher.zip](https://github.com/0iskak/steam-account-switcher/files/7510883/steam-account-switcher.zip)

**Comment by codebreaker332** [comment]
thank you very much bro
